---
- hosts: all
  name: setup cart service
  gather_facts: false
  become: true
  tasks:
    - name: setup nodejs repo
      ansible.builtin.shell: curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

    - name: copy user service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: install nodejs
      ansible.builtin.dnf:
        name: 
          - nodejs
          - unzip
        state: present

    - name: create app user
      ansible.builtin.user:
        name: appuser
        shell: /bin/false

    - name: create app direcotry
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        mode: o-rwx
        state: directory

    - name: download code
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/cart.zip
        dest: /app
        remote_src: yes

    - name: build code
      ansible.builtin.shell: npm install --production

    - name: cart service enable and restart
      ansible.builtin.systemd_service:
        name: cart
        enabled: true
        state: restarted
        daemon_reload: true