---
- hosts: all
  name: setup orders service
  gather_facts: false
  become: true
  tasks: 
    - name: Install Java 21
      ansible.builtin.dnf:
        name:
          - java-21-openjdk
          - java-21-openjdk-devel
          - maven 
          - mysql8.4

    - name: copy orders service
      ansible.builtin.copy:
        src: orders.service
        dest: /etc/systemd/system/orders.service

    - name: create app user
      ansible.builtin.user:
        name: appuser
        shell: /bin/false

    - name: create app direcotry
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        mode: o-rwx
        state: directory

    - name: download code
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/orders.zip
        dest: /app
        remote_src: yes    

    - name: build code with maven
      ansible.builtin.shell: mvn clean package -DskipTests
      arg:
        chdir: /app

    - name: copy jar file
      ansible.builtin.copy: 
        src: /app/target/orders.jar
        dest: /app/orders.jar
        remote_src: yes

    - name: start and enable service
      ansible.builtin.systemd_service:
        name: orders
        state: restarted
        enabled: yes
        daemon_reload: yes