---
- hosts: all
  name: setup shipping service
  gather_facts: false
  become: true
  tasks:
    - name: Install Java 21
      ansible.builtin.dnf:
        name:
          - java-21-openjdk
          - java-21-openjdk-devel
          - maven 
          - mysql8.4
          
    - name: copy shipping service
      ansible.builtin.copy:
        src: shipping.service
        dest: /etc/systemd/system/shipping.service

    - name: create app user
      ansible.builtin.user:
        name: appuser
        shell: /bin/false

    - name: create app direcotry
      ansible.builtin.file:
        path: /app
        owner: appuser
        group: appuser
        mode: o-rwx
        state: directory

    - name: download code
      ansible.builtin.unarchive:
        src: https://raw.githubusercontent.com/raghudevopsb89/roboshop-microservices/main/artifacts/shipping.zip
        dest: /app
        remote_src: yes

    - name: build code with maven
      ansible.builtin.shell: mvn clean package -DskipTests
      arg:
        chdir: /app

    - name: copy jar file
      ansible.builtin.copy: 
        src: /app/target/shipping.jar
        dest: /app/shipping.jar
        remote_src: yes

    - name: setup schema
      ansible.builtin.shell: mysql -h mysql.naresh-training.online -u root -pRoboShop@1 < db/schema.sql
      args:
          chdir: /app

    - name: setup app user schema
      ansible.builtin.shell: mysql -h mysql.naresh-training.online -u root -pRoboShop@1 < db/app-user.sql
      args:
          chdir: /app        

    - name: start and enable service
      ansible.builtin.systemd_service:
        name: shipping
        state: restarted
        enabled: yes
        daemon_reload: yes