---
- hosts: all
  name: setup valkey service
  gather_facts: false
  become: true
  tasks:
    - name: instal valkey
      ansible.builtin.dnf:
        name: valkey
        state: present

    - name: update valk conf file
      ansible.builtin.shell : |
        sed -i "s/bind 127.0.0.1/bind 0.0.0.0/" /etc/valkey/valkey.conf
        sed -i "s/protected-mode yes/protected-mode no/" /etc/valkey/valkey.conf

    - name: enable & start service
      ansible.builtin.systemd_service:
        name: valkey
        state: restarted
        enabled: yes
        daemon_reload: yes
